# Author: NNB <nnbnh@protonmail.com>

"ui.menu" = { fg = "light-gray", bg = "gray" }
"ui.menu.selected" = { modifiers = ["reversed"] }
"ui.linenr" = { fg = "default", bg = "default" }
"ui.linenr.selected" = { fg = "white", bg = "gray", modifiers = ["bold"] }
"ui.popup" = { bg = "gray" }
"ui.window" = { bg = "gray" }
"ui.selection" = { bg = "gray", modifiers = ["reversed"] }
"comment" = { fg = "green", modifiers = ["italic"] }
"ui.statusline" = { fg = "green", bg = "gray", modifiers = ["bold"] }
"ui.statusline.inactive" = { fg = "white", bg = "gray" }
"ui.statusline.insert" = { fg = "gray", bg = "blue", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "gray", bg = "magenta", modifiers = ["bold"] }
"ui.help" = { fg = "white", bg = "black" }
"ui.cursor" = { fg = "light-gray", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "light-gray", modifiers = ["reversed"] }
"ui.virtual.whitespace" = "light-gray"
"ui.virtual.jump-label" = { fg = "blue", bg = "gray", modifiers = ["bold"] }
"ui.virtual.ruler" = { bg = "black" }
"ui.virtual.indent-guide" = { fg = "gray" }
"variable" = { fg = "cyan", modifiers = ["dim"] }
"constant.numeric" = "yellow"
"constant" = "yellow"
"attribute" = "yellow"
"type" = { fg = "blue", modifiers = ["dim"] }
"ui.cursor.match" = { fg = "light-yellow", modifiers = ["italic", "underlined"] }
"string"  = "red"
"variable.other.member" = "light-green"
"constant.character.escape" = "light-cyan"
"function" = "blue"
"constructor" = "light-blue"
"special" = "light-blue"
"keyword" = { fg = "yellow", modifiers = ["dim"] }
"label" = "magenta"
"namespace" = { fg = "magenta", modifiers = ["dim"] }

"markup.heading" = "light-blue"
"markup.list" = "light-red"
"markup.bold" = { fg = "light-yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "light-magenta", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "yellow", modifiers = ["underlined"] }
"markup.link.text" = "light-red"
"markup.quote" = "light-cyan"
"markup.raw" = "light-green"

"diff.plus" = { fg = "light-green", modifiers = ["dim"] }
"diff.delta" = { fg = "yellow", modifiers = ["dim"] }
"diff.minus" = { fg = "light-red", modifiers = ["dim"] }

"diagnostic" = { modifiers = ["underlined"] }
"ui.gutter" = { bg = "gray" }
"ui.gutter.selected" = { bg = "default" }
"info" = "light-blue"
"hint" = "gray"
"debug" = "gray"
"warning" = "yellow"
"error" = "light-red"
