
# A unofficial port of VIM's zenburn theme: https://github.com/jnurmine/Zenburn/

"ui.background" = { bg = "bg" }
"ui.menu" = { fg = "#9f9f9f", bg = "uibg" }
"ui.menu.selected" = { fg = "#d0d0a0", bg = "#242424", modifiers = ["bold"] }
"ui.linenr" = { fg = "fg", bg = "bg"}
"ui.linenr.selected" = { fg = "blue", modifiers = ["bold"]}
"ui.popup" = { bg = "uibg" }
"ui.selection" = { bg = "bgp3" }
"ui.selection.primary" = { bg = "bgp3", modifiers = ["bold"] }
"comment" = { fg = "green", modifiers = ["italic"] }
"ui.virtual.inlay-hint" = { fg = "fgm1" }
"comment.block.documentation" = { fg = "bgm1", modifiers = ["bold"] }
"ui.statusline" = { bg = "bgp2", fg = "green" }
"ui.statusline.inactive" = { fg = 'fgm1', bg = 'bgp2' }
"ui.cursor" = { bg = "fg", fg = "bg", modifiers = ["bold"] }
"ui.text" = { fg = "fg"}
"operator" = { fg = "fgm2" , modifiers = []}
"variable" = "orange"
"variable.builtin" = {fg = "blue", modifiers = ["bold"]}
"constant.numeric" = "green"
"constant" = { fg = "greenp1", modifiers = ["bold"] }
"type" = { fg = "#dfdfbf", modifiers = ["bold"] }
"ui.cursor.match" = { bg = "fgm1", modifiers = ["bold"] }
"string"  = "red"
"variable.other.member" = "blue"
"constant.character.escape" = { fg = "#dca3a3", modifiers = ["bold"]}
"function" = "blue"
"function.macro" = { fg = "#ffcfaf", modifiers = ["bold"] }
"special" = "#cfbfaf"
"keyword" = { fg = "#f0dfaf", modifiers = ["bold"]}
"keyword.storage-class" = { fg = "#c3bf9f", modifiers = ["bold"]}
"label" = { fg = "#dfcfaf", modifiers = ["underlined"] }
"ui.help" = { fg = "white", bg = "black" }
"ui.virtual.ruler" = { bg = "#484848" }
"ui.virtual.whitespace" = { fg = "#5b605e", modifiers = ["bold"]}

"punctuation.delimiter" = "#8f8f8f"

"ui.virtual.indent-guide" = "#4f4f4f"

"diff.plus" = {fg = "#709080"}
"diff.delta" = {fg = "#464646"}
"diff.minus" = {fg = "#cc9393"}

"diagnostic" = {bg = "statusbg"}
"diagnostic.error" = { fg = "errorfg", bg = "errorbg"}
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }
"ui.gutter" = { bg = "statusbg" }
"hint" = {fg = "numeric", bg = "statusbg"}
"warning" = "numeric"
"error" = "errorfg"

[palette]
comment = "#7f9f7f"
constant = "#dca3a3"
normal = "#dcdccc"
todo = "#dfdfdf"
errorfg = "#e37170"
errorbg = "#3d3535"
statusbg = "#313633"
numeric = "#8cd0d3"


fgp1="#FFFFEF"
fg="#DCDCCC"
fgm05="#989888"
fgm1="#656555"
bgm2="#000000"
bgm1="#0C0C0C"
bgm05="#121212"
bg="#1C1C1C"
uibg = "#2c2e2e"
bgp05="#222222"
bgp1="#2C2C2C"
bgp2="#3F3F3F"
bgp3="#4C4C4C"
redp1="#DCA3A3"
red="#CC9393"
redm1="#BC8383"
redm2="#AC7373"
redm3="#9C6363"
redm4="#8C5353"
orange="#DFAF8F"
yellow="#F0DFAF"
yellowm1="#E0CF9F"
yellowm2="#D0BF8F"
yellowm4="#B09F6F"
greenm2="#4F6F4F"
greenm1="#5F7F5F"
green="#7F9F7F"
greenp1="#8FB28F"
greenp2="#9FC59F"
greenp3="#AFD8AF"
greenp4="#BFEBBF"
cyan="#93E0E3"
bluep3="#3c3c45"
bluep1="#94BFF3"
blue="#8CD0D3"
bluem1="#7CB8BB"
bluem2="#6CA0A3"
bluem3="#5C888B"
bluem4="#4C7073"
bluem5="#366060"
magentam1="#BCA3A3"
magenta="#C0BED1"

 
