theme = "passthrough"

[editor]
rulers = [80]
bufferline = "multiple"
jump-label-alphabet = "aidpxrumwfcltn"
color-modes = true
line-number = "relative"
text-width = 80

[editor.cursor-shape]
insert = "bar"

[keys.normal]
C-a = "goto_line_start"
C-e = "goto_line_end"
C-n = "move_visual_line_down"
C-p = "move_visual_line_up"
C-f = "move_char_right"
C-b = "move_char_left"
C-g = "collapse_selection"

[keys.select]
C-a = "goto_line_start"
C-e = "goto_line_end"
C-n = "move_visual_line_down"
C-p = "move_visual_line_up"
C-f = "move_char_right"
C-b = "move_char_left"

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-modification-indicator"]
center = ["file-name"]
right = ["file-type", "version-control", "workspace-diagnostics", "diagnostics", "selections", "register", "position", "file-encoding"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "╎" "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.soft-wrap]
enable = true

